root = "."
tmp_dir = "tmp"
include_ext = ["go", "yaml", "yml", "tpl"]

[slot-game1]
cmd = "go run cmd/slot-game1/main.go"
delay = 1000
exclude_dir = ["tmp", "vendor", "testdata"]
exclude_file = []

[auth-service]
cmd = "go run cmd/auth-service/main.go"
delay = 1000
exclude_dir = ["tmp", "vendor", "testdata"]
exclude_file = []

[build]
  cmd = "go build -o ./tmp/app ./cmd/api/main.go"
  bin = "./tmp/app"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "redis_data"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_ext = ["go", "json", "yaml", "toml"]

[log]
  time = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"