services:
  # 主應用服務
  slot-game1:
    image: passon/slot-game1-service:lastest
    container_name: slot-game1-service
    restart: unless-stopped
    ports:
      - "3000:3000"  # 假設應用監聽 3000 端口
    environment:
      - NACOS_HOST=172.237.27.51
      - NACOS_PORT=8848
      - NACOS_NAMESPACE=test_golang
      - NACOS_GROUP=TEST_GOLANG_ENVS
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=xup6jo3fup6
    # depends_on:
    #   - postgres
    #   - redis
    networks:
      - slot-game-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 15s
    volumes:
      - slot-game1-logs:/app/logs

# 定義網絡
networks:
  slot-game-network:
    driver: bridge

# 定義卷
volumes:
  slot-game1-logs:
    driver: local